### ISSUE TITLE
Build docker and host image for SQL Server service

### ISSUE THREAD

**Issue by datnguye** [datnguye/dbt-resto#21]
SQL Server Version: 2022

Following the instruction to [Customize the SQL Server Container](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-configure?view=sql-server-ver16&pivots=cs1-bash).

Base image is [Microsoft SQL Server - Ubuntu based images](https://hub.docker.com/_/microsoft-mssql-server)

**Comment by Yashar8991** [comment]
which version? developer?

**Comment by datnguye** [comment]
Hi @Yashar8991 The initial intent is to replicate this image `ghcr.io/dbt-msft/dbt-sqlserver:server-2022`, and I think this is community version.

Do you plan to try this out with a PR? This repo is for me to practice stuff but will be more than welcome everyone to join 👍 🎉

**Comment by datnguye** [comment]
@Yashar8991 Answering your question correctly, we will control the Edition by the env named: `MSSQL_PID `

By default, it is DEVELOPER.

**Docs**: MSSQL_PID is the Product ID (PID) or Edition that the container will run with.

Acceptable values:

- Developer : This will run the container using the Developer Edition (this is the default if no MSSQL_PID environment variable is supplied)
- Express : This will run the container using the Express Edition
- Standard : This will run the container using the Standard Edition
- Enterprise : This will run the container using the Enterprise Edition
- EnterpriseCore : This will run the container using the Enterprise Edition Core

**Comment by datnguye** [comment]
**Pipeline**: [jobs:publish-sqlserver](https://github.com/datnguye/dbt-resto/blob/main/.github/workflows/publish-docker.yml#L12)

**Image available:** [sqlserver-2022](https://github.com/datnguye/dbt-resto/pkgs/container/dbt-resto/91132463?tag=sqlserver-2022)
